const moods = [
    "Romantic 💕",
    "Dreamy 🌙",
    "Tender 💖",
    "Affectionate 😍",
    "Passionate 🔥",
    "Intimate 🌹",
    "Loving ❤️",
    "Enamored 😊",
    "Blissful 🥰",
    "Warm ☺️",
    "Cozy 🛋️",
    "Euphoric 🌟",
    "Ecstatic 🤩",
    "Infatuated 💘",
    "Swooning 😌",
    "Adoring 🌼",
    "Cherished 💞",
    "Sensual 🎇",
    "Devoted 💌",
    "Content 😌",
    "Happy 😊",
    "Delighted 😄",
    "Joyful 😁",
    "Smitten 😻",
    "Grateful 🙏",
    "Amorous 💑",
    "Elated 🥳",
    "Fulfilled 😇",
    "Cuddly 🐻",
    "Sentimental 💭",
    "Peaceful ☮️",
    "Enchanted ✨",
    "Radiant 🌞",
    "Bubbly 🥂",
    "Hopeful 🌼",
    "Fancy 💫",
    "Giddy 🎉",
    "Blushing 😳",
    "Heartfelt 💖",
    "Excited 😃",
    "Whimsical 🌈",
  ];
  
export default moods;